version: '3.3'

services:
  app:
    image: podyn
    volumes:
      - ./:/app/src
    environment:
      AWS_REGION: us-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DYNAMODB_ENDPOINT: http://docker.for.mac.localhost:8000
      POSTGRES_JDBC_URL: "jdbc:postgresql://db:5432/podyn?currentSchema=public&user=podyn&password=podyn"

  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: podyn
      POSTGRES_PASSWORD: podyn
      POSTGRES_DB: podyn
